#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend somara.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 134253-web-01 34.232.70.152:80
        server 134253-web-02 100.25.161.248:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
