#!/usr/bin/env bash
# A Bash script that creates an RSA key pair of bit size 4096 with passphrase
[2;2R[3;1R[>77;30603;0c]10;rgb:bfbf/bfbf/bfbf]11;rgb:0000/0000/0000# betty.
ssh-keygen -b 4096 -f school -N betty
